config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"
  resources :salesmen
  resources :riders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rider.rb
class Rider < ApplicationRecord
	# mount_uploader :cnic, :driving_license, :reg_copy, :cv, AvatarUploader
	enum gender: [:male, :female]
end

app/models/salesman.rb
class Salesman < ApplicationRecord
	validates :name, :email, :phone, :gender, :age, :qualification, :work_experience, :cv, :job_type, presence: :true
	enum gender: [:male, :female]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  # GET /riders
  # GET /riders.json
  def index
    @riders = Rider.all
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
  end

  # GET /riders/new
  def new
    @rider = Rider.new
  end

  # GET /riders/1/edit
  def edit
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = Rider.new(rider_params)

    respond_to do |format|
      if @rider.save
        format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
        format.json { render :show, status: :created, location: @rider }
      else
        format.html { render :new }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /riders/1
  # PATCH/PUT /riders/1.json
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url, notice: 'Rider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = Rider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.require(:rider).permit(:name, :email, :phone, :gender, :age, :qualification, :work_experience, :ice_number, :cnic, :driving_license, :reg_copy, :cv)
    end
end

app/controllers/salesmen_controller.rb
class SalesmenController < ApplicationController
  before_action :set_salesman, only: [:show, :edit, :update, :destroy]

  # GET /salesmen
  # GET /salesmen.json
  def index
    @salesmen = Salesman.all
  end

  # GET /salesmen/1
  # GET /salesmen/1.json
  def show
  end

  # GET /salesmen/new
  def new
    @salesman = Salesman.new
  end

  # GET /salesmen/1/edit
  def edit
  end

  # POST /salesmen
  # POST /salesmen.json
  def create
    @salesman = Salesman.new(salesman_params)

    respond_to do |format|
      if @salesman.save
        format.html { redirect_to @salesman, notice: 'Salesman was successfully created.' }
        format.json { render :show, status: :created, location: @salesman }
      else
        flash[:toast] = @salesman.errors.full_messages.first
        format.html { render :new }
        format.json { render json: @salesman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salesmen/1
  # PATCH/PUT /salesmen/1.json
  def update
    respond_to do |format|
      if @salesman.update(salesman_params)
        format.html { redirect_to @salesman, notice: 'Salesman was successfully updated.' }
        format.json { render :show, status: :ok, location: @salesman }
      else
        format.html { render :edit }
        format.json { render json: @salesman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salesmen/1
  # DELETE /salesmen/1.json
  def destroy
    @salesman.destroy
    respond_to do |format|
      format.html { redirect_to salesmen_url, notice: 'Salesman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salesman
      @salesman = Salesman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salesman_params
      params.require(:salesman).permit(:name, :email, :phone, :gender, :age, :qualification, :work_experience, :cv, :job_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/helpers/salesmen_helper.rb
module SalesmenHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kami</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  </head>

  <body>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/riders/_form.html.erb
<%= form_for(rider) do |f| %>
  <% if rider.errors.any? %>
    <div id="">
      <h2><%= pluralize(rider.errors.count, "error") %> prohibited this rider from being saved:</h2>

      <ul>
      <% rider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender, options_for_select([['Male', 'male'], ['Female', 'female']]) %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age, min: 15 %>
  </div>

  <div class="field">
    <%= f.label :qualification %>
    <%= f.text_field :qualification %>
  </div>

  <div class="field">
    <%= f.label :work_experience %>
    <%= f.text_field :work_experience %>
  </div>

  <div class="field">
    <%= f.label :ice_number %>
    <%= f.text_field :ice_number %>
  </div>

  <div class="field">
    <%= f.label :cnic %>
    <%= f.file_field :cnic %>
  </div>

  <div class="field file-path-wrapper">
    <%= f.label :driving_license %>
    <%= f.file_field :driving_license, class: "file-path validate" %>
  </div>

  <div class="field">
    <%= f.label :reg_copy %>
    <%= f.file_field :reg_copy %>
  </div>

  <div class="field">
    <%= f.label :cv %>
    <%= f.file_field :cv %>
  </div>

  <div class="btn waves-effect waves-light">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('select').material_select();
  });
</script>

app/views/riders/edit.html.erb
<h1>Editing Rider</h1>

<%= render 'form', rider: @rider %>

<%= link_to 'Show', @rider %> |
<%= link_to 'Back', riders_path %>

app/views/riders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Riders</h1>

<table class="bordered striped centered responsive-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Qualification</th>
      <th>Work experience</th>
      <th>Ice number</th>
      <th>Cnic</th>
      <th>Driving license</th>
      <th>Reg copy</th>
      <th>Cv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @riders.each do |rider| %>
      <tr>
        <td><%= rider.name %></td>
        <td><%= rider.email %></td>
        <td><%= rider.phone %></td>
        <td><%= rider.gender %></td>
        <td><%= rider.age %></td>
        <td><%= rider.qualification %></td>
        <td><%= rider.work_experience %></td>
        <td><%= rider.ice_number %></td>
        <td><%= rider.cnic %></td>
        <td><%= rider.driving_license %></td>
        <td><%= rider.reg_copy %></td>
        <td><%= rider.cv %></td>
        <td><%= link_to 'Show', rider %></td>
        <td><%= link_to 'Edit', edit_rider_path(rider) %></td>
        <td><%= link_to 'Destroy', rider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Rider', new_rider_path, class: "btn waves-effect waves-light" %>

app/views/riders/new.html.erb
<h1>New Rider</h1>

<%= render 'form', rider: @rider %>

<%#= link_to 'Back', riders_path %>

app/views/riders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rider.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @rider.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @rider.phone %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @rider.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @rider.age %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @rider.qualification %>
</p>

<p>
  <strong>Work experience:</strong>
  <%= @rider.work_experience %>
</p>

<p>
  <strong>Ice number:</strong>
  <%= @rider.ice_number %>
</p>

<p>
  <strong>Cnic:</strong>
  <%= @rider.cnic %>
</p>

<p>
  <strong>Driving license:</strong>
  <%= @rider.driving_license %>
</p>

<p>
  <strong>Reg copy:</strong>
  <%= @rider.reg_copy %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @rider.cv %>
</p>

<%= link_to 'Edit', edit_rider_path(@rider) %> |
<%= link_to 'Back', riders_path %>

app/views/salesmen/_form.html.erb
<%= form_for(salesman) do |f| %>
  <% if salesman.errors.any? %>
    <div id="">
      <h2><%= pluralize(salesman.errors.count, "error") %> prohibited this salesman from being saved:</h2>

      <ul>
      <% salesman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <!-- <select>
      <option value="" disabled selected>choose</option>
      <option value="0">Male</option>\
      <option value="1">Female</option>
    </select> -->
    <%= f.select :gender, options_for_select([['Male', 'male'], ['Female', 'female']]) %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age, min: 15 %>
  </div>

  <div class="field">
    <%= f.label :qualification %>
    <%= f.text_field :qualification %>
  </div>

  <div class="field">
    <%= f.label :work_experience %>
    <%= f.text_field :work_experience %>
  </div>

  <div class="field">
    <%= f.label :job_type %>
    <%= f.number_field :job_type %>
  </div>

  <div class="field">
    <%= f.label :cv %>
    <%= f.file_field :cv %>
  </div>

  <div class="btn waves-effect waves-light">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('select').material_select();
  });
</script>

app/views/salesmen/edit.html.erb
<h1>Editing Salesman</h1>

<%= render 'form', salesman: @salesman %>

<%= link_to 'Show', @salesman %> |
<%= link_to 'Back', salesmen_path %>

app/views/salesmen/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salesmen</h1>

<table class="bordered striped centered responsive-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Qualification</th>
      <th>Work experience</th>
      <th>Cv</th>
      <th>Job type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salesmen.each do |salesman| %>
      <tr>
        <td><%= salesman.name %></td>
        <td><%= salesman.email %></td>
        <td><%= salesman.phone %></td>
        <td><%= salesman.gender %></td>
        <td><%= salesman.age %></td>
        <td><%= salesman.qualification %></td>
        <td><%= salesman.work_experience %></td>
        <td><%= salesman.cv %></td>
        <td><%= salesman.job_type %></td>
        <td><%= link_to 'Show', salesman %></td>
        <td><%= link_to 'Edit', edit_salesman_path(salesman) %></td>
        <td><%= link_to 'Destroy', salesman, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salesman', new_salesman_path, class: "btn waves-effect waves-light"%>

app/views/salesmen/new.html.erb
<h1>New Salesman</h1>

<%= render 'form', salesman: @salesman %>

<%#= link_to 'Back', salesmen_path %>

app/views/salesmen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @salesman.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @salesman.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @salesman.phone %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @salesman.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @salesman.age %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @salesman.qualification %>
</p>

<p>
  <strong>Work experience:</strong>
  <%= @salesman.work_experience %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @salesman.cv %>
</p>

<p>
  <strong>Job type:</strong>
  <%= @salesman.job_type %>
</p>

<%= link_to 'Edit', edit_salesman_path(@salesman) %> |
<%= link_to 'Back', salesmen_path %>